### ISSUE TITLE
how to use schema?

### ISSUE THREAD

**Issue by LoadingSugar** [THUDM/GATNE#15]
if graph content item nodes and user nodes[user1  item199，user2  item65，...，user89 item889]，what is each line of the node_type.txt，Can give concrete examples about -- schema  and node_type.txt；if   dataset contains several node types and do not use schema，i can distinguish  node type by feature.txt (feature.txt columns can be: node_id   user_age  user_job  item_size  item_price.  for user nodes,the item_size  and item_price is 0), whether this method works？

**Comment by cenyk1230** [comment]
You can give unique numbers to nodes (e.g., 1-n for user_1-user_n and (n+1)-(n+m) for item_1-item_m). Then the node type file can be "1 user\n 2 user\n ... n user\n n+1 item\n ... n+m item\n". The schema is then "user-item-user". 

If the schema is not specified, our code will use a normal random walk rather than a meta-path-based random walk. It probably works though ignoring the node types.
