### ISSUE TITLE
How to generate train, test and valid data

### ISSUE THREAD

**Issue by AnonymizedAccount** [THUDM/GATNE#72]
Hi, Thanks for your great work. 
First of all, I am new to deep learning, and I would like to ask you about data generation: how did you build your train, test, and valid data from the input graph? I used the following method from numpy : 'train, validate, test = np.split(df.sample(frac=1), [int(.6*len(df)), int(.8*len(df))])
' but it did not give me good results.
I would be so grateful for your help!

**Comment by cenyk1230** [comment]
Hi @AnonymizedAccount,

Thank you for your interest in our work. In our experiments, nodes in the validation and testing sets should be all in the training set; otherwise, these nodes which are not in the training set will not have embeddings for evaluation. A simple way is to remove these nodes from validation and testing sets.

**Comment by AnonymizedAccount** [comment]
Thank you for your reply :)!
But I have another question. What about the size of each dataset (train, test and valid)? Is it necessary to use 60% of data for training, 20% for test, and 20% for validation? What's the appropriate setting should I use?

**Comment by cenyk1230** [comment]
In our experimental setting, we split the original dataset by 0.85/0.05/0.10 for training, validation, and testing.
